// Generated by app-wabbit-dev setup. Do not edit by hand.
// managed-integrity-v1: CnNmNxrJVG7
//
// This file is generated from workspace configuration in root.clj.
// To change it, update root.clj and regenerate
// with the dev command, for example:
//   dev setup <project-or-repo>
// For durable imperative Gradle logic, use build.extra.gradle.kts beside this file.
// Direct edits to this file will be overwritten the next time setup runs.

import org.jetbrains.dokka.gradle.DokkaExtension
import org.jetbrains.dokka.gradle.engine.plugins.DokkaHtmlPluginParameters
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

fun String.parseWabbitBooleanFlag(flagName: String): Boolean =
    when (trim().lowercase()) {
        "true" -> true
        "false" -> false
        else -> error("$flagName must be true or false, got '$this'")
    }

val useMavenLocalArtifacts =
    providers.gradleProperty("wabbit.useMavenLocalArtifacts")
        .orElse(providers.environmentVariable("WABBIT_USE_MAVEN_LOCAL_ARTIFACTS"))
        .map { it.parseWabbitBooleanFlag("wabbit.useMavenLocalArtifacts") }
        .orElse(false)
        .get()

repositories {
    if (useMavenLocalArtifacts) {
        mavenLocal {
            content {
                includeGroup("one.wabbit")
                includeGroupByRegex("one\\.wabbit\\..+")
            }
        }
    }
    google()
    mavenCentral()

    maven("https://jitpack.io")
}

group   = "one.wabbit"

version = "1.0.2"

plugins {
    kotlin("jvm")
    id("org.jetbrains.dokka")
    id("org.jetbrains.kotlinx.kover")

    id("one.wabbit.no-globals")

    id("one.wabbit.acyclic")

    id("maven-publish")

    id("com.vanniktech.maven.publish")
}

mavenPublishing {
    coordinates("one.wabbit", "kotlin-minilog", project.version.toString())
    publishToMavenCentral()
    signAllPublications()
    pom {
        name.set("kotlin-minilog")
        description.set("kotlin-minilog")
        url.set("https://github.com/wabbit-corp/kotlin-minilog")
        licenses {
            license {
                name.set("GNU Affero General Public License v3.0 or later")
                url.set("https://spdx.org/licenses/AGPL-3.0-or-later.html")
            }
        }
        developers {
            developer {
                id.set("wabbit-corp")
                name.set("Wabbit Consulting Corporation")

                email.set("wabbit@wabbit.one")

            }
        }
        scm {
            url.set("https://github.com/wabbit-corp/kotlin-minilog")
            connection.set("scm:git:git://github.com/wabbit-corp/kotlin-minilog.git")
            developerConnection.set("scm:git:ssh://git@github.com/wabbit-corp/kotlin-minilog.git")
        }
    }
}

val localPublishRequested =
    gradle.startParameter.taskNames.any { taskName -> "MavenLocal" in taskName }

if (localPublishRequested) {
    tasks.withType<org.gradle.plugins.signing.Sign>().configureEach {
        enabled = false
    }
}

dependencies {
    implementation("one.wabbit:kotlin-java-escape:1.0.1")

    testImplementation(kotlin("test"))

    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
}

java {
    targetCompatibility = JavaVersion.toVersion(21)
    sourceCompatibility = JavaVersion.toVersion(21)
}

val configuredVersionString = version.toString()

tasks.register("printVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        println(inputs.properties["configuredVersion"])
    }
}

tasks.register("assertReleaseVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(!versionString.endsWith("+dev-SNAPSHOT")) {
            "Release publishing requires a non-snapshot version, got $versionString"
        }
        val refType = System.getenv("GITHUB_REF_TYPE") ?: ""
        val refName = System.getenv("GITHUB_REF_NAME") ?: ""
        if (refType == "tag" && refName.isNotBlank()) {
            val expectedTag = "v$versionString"
            require(refName == expectedTag) {
                "Git tag $refName does not match project version $versionString"
            }
        }
    }
}

tasks.register("assertSnapshotVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(versionString.endsWith("+dev-SNAPSHOT")) {
            "Snapshot publishing requires a +dev-SNAPSHOT version, got $versionString"
        }
        require((System.getenv("GITHUB_REF_TYPE") ?: "") != "tag") {
            "Snapshot publishing must not run from a tag ref"
        }
    }
}

tasks {
    withType<Test> {
        jvmArgs("-ea")

    }
    withType<JavaCompile> {
        options.encoding = Charsets.UTF_8.name()
        options.release.set(21)
    }
    withType<Javadoc> {
        options.encoding = Charsets.UTF_8.name()
    }

    withType<KotlinCompile> {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
            freeCompilerArgs.add("-Xcontext-parameters")

            freeCompilerArgs.addAll(
                "-P",
                "plugin:one.wabbit.acyclic:compilationUnits=enabled",
            )

        }
    }

    jar {
        setProperty("zip64", true)

    }
}

// Kover Configuration
kover {
    // useJacoco() // This is the default, can be specified if you want to be explicit
    // reports {
    //     // Configure reports for the default test task.
    //     // Kover tries to infer the variant for simple JVM projects.
    //     // If you have specific build types/flavors, you'd configure them here as variants.
    //     variant() { // Or remove "debug" for a default JVM setup unless you have variants
    //         html {
    //             // reportDir.set(layout.buildDirectory.dir("reports/kover/html")) // Uncomment to customize output
    //             // title.set("kotlin-minilog Code Coverage") // Uncomment to customize title
    //         }
    //         xml {
    //             // reportFile.set(layout.buildDirectory.file("reports/kover/coverage.xml")) // Uncomment to customize output
    //         }
    //     }
    // }
}

plugins.withId("org.jetbrains.dokka") {
    afterEvaluate {
        extensions.findByType(DokkaExtension::class)?.apply {
            moduleName.set("kotlin-minilog")
            dokkaPublications.named("html").configure {
                suppressInheritedMembers.set(true)
                failOnWarning.set(true)
            }
            dokkaSourceSets.named("main").configure {
                val dokkaModuleFile = file("docs/dokka-module.md")
                if (dokkaModuleFile.exists()) {
                    includes.from(dokkaModuleFile)
                }

                sourceLink {
                    localDirectory.set(file("src/main/kotlin"))
                    remoteUrl("https://github.com/wabbit-corp/kotlin-minilog/tree/master/src/main/kotlin")
                    remoteLineSuffix.set("#L")
                }

            }
            pluginsConfiguration.named(DokkaHtmlPluginParameters.DOKKA_HTML_PARAMETERS_NAME).configure {
                (this as DokkaHtmlPluginParameters).footerMessage.set("(c) Wabbit Consulting Corporation")
            }
        }
    }
}

val extraBuildFile = file("build.extra.gradle.kts")
if (extraBuildFile.isFile) {
    apply(from = extraBuildFile)
}
